version: "3"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - C:/Users/Equipo_03/Desktop/pruebas/:/app/ # Monta un volumen para que la carpeta del host esté disponible en el contenedor en la ruta /app/ 
    ports:
      - "3000:3000"
